name: Build

on:
  push:
    branches: [main]

jobs:
  tests-front:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: ionic serve
          browser: chrome

  build-and-push-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}'
      - name: Building and pushing the image
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: gcr.io
          project_id: ${{ secrets.PROJECT_ID }}
          image_name: spotiapp-front
          image_tag: latest, ${{ github.sha }}
          dockerfile: ./Dockerfile
          context: ./ 
    